name: Aggregation
description: Apply `horizontal` aggregation
aggregation:
  metrics:
    - 'cpu/utilization'
  type: 'horizontal'
initialize:
  plugins:
    cloud-metadata:
      path: builtin
      method: CSVLookup
      config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-aws-instances.csv
        query:
          instance-class: cloud/instance-type
        output: ['cpu-cores-utilized', 'vcpus-allocated']
      parameter-metadata:
        inputs:
          cpu/utilization:
            unit: percentage
            description: refers to CPU utilization.
            aggregation-method:
              time: avg
              component: avg
tree:
  children:
    application:
      pipeline:
        compute:
          - cloud-metadata
      children:
        uk-west:
          children:
            server-1:
              inputs:
                - timestamp: '2024-02-26 00:00:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 89
                - timestamp: '2024-02-26 00:05:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 59
            server-2:
              inputs:
                - timestamp: '2024-02-26 00:00:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 24
                - timestamp: '2024-02-26 00:05:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 27
