name: csv-lookup-demo
description: null
tags: null
initialize:
  plugins:
    cloud-metadata:
      path: builtin
      method: CSVLookup
      global-config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/region-metadata.csv
        query:
          cloud-provider: cloud/provider
          cloud-region: cloud/region
        output: '*'
  outputs:
    - yaml
execution:
  command: >-
    /Users/mariamkhalatova/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /Users/mariamkhalatova/Projects/UK/if/src/index.ts -m
    manifests/examples/builtins/csv-lookup/success.yml -o
    manifests/examples/builtins/csv-lookup/success
  environment:
    if-version: 0.4.0
    os: macOS
    os-version: '13.2'
    node-version: 18.14.2
    date-time: 2024-07-02T21:09:37.066Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-core@0.0.10'
      - '@grnsft/if-plugins@v0.3.2 extraneous -> file:../../../../if-models'
      - >-
        @grnsft/if-unofficial-plugins@v0.3.1 extraneous ->
        file:../../../../if-unofficial-models
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - cross-env@7.0.3
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.22.4
  status: success
tree:
  children:
    child:
      pipeline:
        - cloud-metadata
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cloud/provider: Google Cloud
          cloud/region: asia-east1
      outputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cloud/provider: Google Cloud
          cloud/region: asia-east1
          year: 2022
          cfe-region: Taiwan
          em-zone-id: TW
          wt-region-id: TW
          location: Taiwan
          geolocation: 25.0375,121.5625
          cfe-hourly: 0.18
          cfe-annual: nan
          power-usage-efficiency: nan
          net-carbon: 0
          grid-carbon-intensity-24x7: 453
          grid-carbon-intensity-consumption: nan
          grid-carbon-intensity-marginal: nan
          grid-carbon-intensity-production: nan
          grid-carbon-intensity: 453
