name: coefficient-demo
description: failure with ivalid `global-config.input-parameter`
tags:
initialize:
  plugins:
    coefficient:
      method: Coefficient
      path: "builtin"
      global-config:
        input-parameter: 4
        coefficient: 3
        output-parameter: "carbon-product"
tree:
  children:
    child:
      pipeline:
        - coefficient
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          carbon: 30
