name: aggregation-error-wrong-metric
description: a negative test case that fails due to the aggregation feature being passed an incorrect metric
tags:
aggregation:
  metrics:
    - "dummy-param"
  type: "both"
initialize:
  plugins:
    "teads-curve":
      path: "@grnsft/if-unofficial-plugins"
      method: TeadsCurve
      global-config:
        interpolation: spline
    "sum-energy-components":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - cpu/energy
          - network/energy
        output-parameter: energy
    "sci-embodied":
      path: "builtin"
      method: SciEmbodied
    "operational-carbon":
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["energy", "grid/carbon-intensity"]
        output-parameter: "carbon-operational"
    "sci":
      path: "builtin"
      method: Sci
      global-config:
        functional-unit: "requests"
    "time-sync":
      method: TimeSync
      path: "builtin"
      global-config:
        start-time: "2023-12-12T00:00:00.000Z"
        end-time: "2023-12-12T00:01:00.000Z"
        interval: 5
        allow-padding: true
    "group-by":
      path: builtin
      method: GroupBy
tree:
  children:
    child-1:
      pipeline:
        - teads-curve
        - sum-energy-components
        - sci-embodied
        - operational-carbon
        - time-sync
        - sci
      config:
        group-by:
          group:
            - cloud/region
            - cloud/instance-type
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          cloud/instance-type: A1
          cloud/region: uk-west
          duration: 1
          cpu/utilization: 10
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          cpu/utilization: 20
          cloud/instance-type: A1
          cloud/region: uk-west
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          cpu/utilization: 15
          cloud/instance-type: A1
          cloud/region: uk-west
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          cloud/instance-type: A1
          cloud/region: uk-west
          cpu/utilization: 15
    child-2:
      pipeline:
        - teads-curve
        - sci-e
        - sci-embodied
        - sci-o
        - time-sync
        - sci
      config:
        group-by:
          group:
            - cloud/region
            - cloud/instance-type
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          cpu/utilization: 30
          cloud/instance-type: A1
          cloud/region: uk-west
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          cpu/utilization: 28
          cloud/instance-type: A1
          cloud/region: uk-west
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          cpu/utilization: 40
          cloud/instance-type: A1
          cloud/region: uk-west
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          cpu/utilization: 33
          cloud/instance-type: A1
          cloud/region: uk-west
