name: boavizta
description: calls boavizta api
tags:
initialize:
  plugins:
    "boavizta-cpu":
      method: BoaviztaCpuOutput
      path: "@grnsft/if-unofficial-models"
      global-config:
        allocation: LINEAR
        verbose: true
tree:
  children:
    child:
      pipeline:
        - boavizta-cpu
      defaults:
        cpu/number-cores: 24
        cpu/name: Intel® Core™ i7-1185G7
      inputs:
        - timestamp: 2023-07-06T00:00 # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          duration: 3600 # Secs
          cpu/utilization: 18.392
        - timestamp: 2023-08-06T00:00 # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          duration: 3600 # Secs
          cpu/utilization: 16
