name: cloud-instance-metadata
description: example impl invoking Cloud Instance Metadata plugin
tags:
initialize:
  plugins:
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - cloud-metadata
      config:
      inputs:
        - timestamp: 2023-07-06T00:00 # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          cloud/vendor: aws
          cloud/instance-type: m5n.large
          duration: 100
          cpu/utilization: 10
