name: csv-export-demo
description: example exporting output to a csv file
tags:
initialize:
  plugins:
    csv-exporter:
      method: CsvExport
      path: "@grnsft/if-models"
tree:
  children:
    child:
      pipeline:
        - csv-exporter
      config:
        csv-exporter:
          output-path: ./examples/outputs/csv-test.csv
          headers:
            - timestamp
            - duration
            - carbon
            - energy
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          operational-carbon: 0.02
          embodied-carbon: 5
          energy: 3.5
          carbon: 5.02
        - timestamp: 2023-07-06T00:10
          duration: 1
          operational-carbon: 0.03
          embodied-carbon: 4
          energy: 2.9
          carbon: 4.03
