name: e-mem
description:
tags:
initialize:
  plugins:
    e-mem:
      method: EMem
      path: "@grnsft/if-models"
      global-config:
        energy-per-gb: 0.002
tree:
  children:
    child:
      pipeline:
        - e-mem
      config:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          memory/utilization: 40
          memory/capacity: 1
