name: groupby-demo
description: demo pipeline
initialize:
  plugins:
    group-by: 
      path: 'builtin'
      method: GroupBy
tree:
  children:
    my-app:
      pipeline:     
        - group-by
      config:
        group-by:
          group:
            - region
            - cloud/instance-type
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 300 
          cloud/instance-type: A1 
          region: uk-west
          cpu-util: 99
        - timestamp: 2023-07-06T05:00 
          duration: 300 
          cloud/instance-type: A1 
          region: uk-west
          cpu-util: 23	  
        - timestamp: 2023-07-06T10:00
          duration: 300
          cloud/instance-type: A1 
          region: uk-west
          cpu-util: 12
        - timestamp: 2023-07-06T00:00 # note this time restarts at the start timstamp
          duration: 300 
          cloud/instance-type: B1
          region: uk-west
          cpu-util: 11
        - timestamp: 2023-07-06T05:00 
          duration: 300 
          cloud/instance-type: B1
          region: uk-west
          cpu-util: 67
        - timestamp: 2023-07-06T10:00
          duration: 300 
          cloud/instance-type: B1
          region: uk-west
          cpu-util: 1
