name: nesting-demo
description: null
tags:
  kind: web
  complexity: moderate
  category: on-premise
params:
aggregation:
  type: vertical
  metrics:
    - "energy"
initialize:
  plugins:
    teads-curve:
      path: "@grnsft/if-unofficial-plugins"
      method: TeadsCurve
      global-config:
        interpolation: spline
    sci-e:
      path: "@grnsft/if-plugins"
      method: SciE
    sci-m:
      path: "@grnsft/if-plugins"
      method: SciM
    sci-o:
      path: "@grnsft/if-plugins"
      method: SciO
    "time-sync":
      method: TimeSync
      path: "builtin"
      global-config:
        start-time: "2023-12-12T00:00:00.000Z"
        end-time: "2023-12-12T00:01:00.000Z"
        interval: 5
        allow-padding: true
    sci:
      path: "@grnsft/if-plugins"
      method: Sci
      global-config:
        functional-unit: "requests"
        functional-unit-time: "1 minute"
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
        functional-unit-time: "1 min"
      pipeline:
        - teads-curve
        - sci-e
        - sci-m
        - sci-o
        - time-sync
        - sci
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 10
          cpu/utilization: 50
          network/energy: 1
          energy: 1
    child-1:
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
        functional-unit-time: "1 min"
      pipeline:
        - teads-curve
        - sci-e
        - sci-m
        - sci-o
        - time-sync
        - sci
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 10
          cpu/utilization: 30
          network/energy: 1
          energy: 1
