name: pipeline-with-generics-demo
description:
tags:
aggregation:
  metrics:
    - "carbon"
  type: "both"
params:
  - name: energy-sum
    description: "sum of energies"
    unit: "kWh"
    aggregation: sum
initialize:
  plugins:
    "teads-curve":
      path: "@grnsft/if-unofficial-plugins"
      method: TeadsCurve
      global-config:
        interpolation: spline
    "sum":
      path: "@grnsft/if-plugins"
      method: Sum
      global-config:
        input-parameters:
          - cpu/energy
          - network/energy
        output-parameter: energy-sum
    "coefficient":
      path: "@grnsft/if-plugins"
      method: Coefficient
      global-config:
        input-parameter: energy
        coefficient: 2
        output-parameter: energy-doubled
    "sci-m":
      path: "@grnsft/if-plugins"
      method: SciM
    "sci-o":
      path: "@grnsft/if-plugins"
      method: SciO
    "sci":
      path: "@grnsft/if-plugins"
      method: Sci
      global-config:
        functional-unit: "requests"
        functional-unit-time: "1 minute"
    "time-sync":
      method: TimeSync
      path: "builtin"
      global-config:
        start-time: "2023-12-12T00:00:00.000Z"
        end-time: "2023-12-12T00:01:00.000Z"
        interval: 5
        allow-padding: true
tree:
  children:
    child-1:
      pipeline:
        - teads-curve
        - sum
        - sci-m
        - sci-o
        - time-sync
        - coefficient
        - sci
      config:
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
        functional-unit-time: "1 min"
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          cloud/instance-type: A1
          cloud/region: uk-west
          duration: 1
          cpu/utilization: 50
          network/energy: 10
          energy: 5
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          cpu/utilization: 20
          cloud/instance-type: A1
          cloud/region: uk-west
          network/energy: 10
          energy: 5
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          cpu/utilization: 15
          cloud/instance-type: A1
          cloud/region: uk-west
          network/energy: 10
          energy: 5
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          cloud/instance-type: A1
          cloud/region: uk-west
          cpu/utilization: 15
          network/energy: 10
          energy: 5
    child-2:
      pipeline:
        - teads-curve
        - sum
        - sci-m
        - sci-o
        - time-sync
        - coefficient
        - sci
      config:
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
        functional-unit-time: "1 min"
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          cpu/utilization: 30
          cloud/instance-type: A1
          cloud/region: uk-west
          network/energy: 10
          energy: 5
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          cpu/utilization: 28
          cloud/instance-type: A1
          cloud/region: uk-west
          network/energy: 10
          energy: 5
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          cpu/utilization: 40
          cloud/instance-type: A1
          cloud/region: uk-west
          network/energy: 10
          energy: 5
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          cpu/utilization: 33
          cloud/instance-type: A1
          cloud/region: uk-west
          network/energy: 10
          energy: 5
