name: watt-time-demo
description: null
tags: null
initialize:
  plugins:
    mock-observations:
      path: "@grnsft/if-plugins"
      method: MockObservations
      global-config:
        timestamp-from: "2024-03-05T00:00:00.000Z"
        timestamp-to: "2024-03-05T00:10:00.000Z"
        duration: 60
        components:
          - cloud/instance-type: Standard_E64_v3
          - cloud/instance-type: Standard_E64_v4
        generators:
          common:
            cloud/vendor: azure
            cloud/region: westus
            cloud/region-wt-id: CAISO_NORTH
          randint:
            cpu/utilization:
              min: 1
              max: 99
    watttime:
      path: "@grnsft/if-unofficial-plugins"
      method: WattTimeGridEmissions
tree:
  children:
    application:
      pipeline:
        - mock-observations
        - watttime
      config:
      inputs:
