name: time-sync
description: missing config
tags:
initialize:
  output:
    - yaml
  plugins:
    'time-sync':
      method: TimeSync
      path: 'builtin'
      config:
tree:
  children:
    child:
      pipeline:
        compute:
          - time-sync
      inputs:
        - timestamp: '2023-12-12T00:00:00.000Z'
          duration: 3
          energy-cpu: 0.001
        - timestamp: '2023-12-12T00:00:01.000Z'
          duration: 5
          energy-cpu: 0.001
        - timestamp: '2023-12-12T00:00:06.000Z'
          duration: 7
          energy-cpu: 0.001
        - timestamp: '2023-12-12T00:00:13.000Z'
          duration: 30
          energy-cpu: 0.001
