name: time-sync
description: failure with `config.start-time` being later than `config.end-time`
tags:
initialize:
  plugins:
    "time-sync":
      method: TimeSync
      path: "builtin"
      config:
        start-time: "2023-12-12T00:01:00.000Z"
        end-time: "2023-12-12T00:00:00.000Z"
        interval: 5
        allow-padding: true
tree:
  children:
    child:
      pipeline:
        compute:
          - time-sync
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          energy-cpu: 0.001
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          energy-cpu: 0.001
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          energy-cpu: 0.001
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          energy-cpu: 0.001
