name: Aggregation
description: Fails with missing metric in inputs.
aggregation:
  metrics:
    - 'cpu/utilization'
  type: 'both'
initialize:
  plugins:
    cloud-metadata:
      path: builtin
      method: CSVLookup
      global-config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-aws-instances.csv
        query:
          instance-class: cloud/instance-type
        output: ['cpu-cores-utilized', 'vcpus-allocated']            
tree:
  children:
    application:
      pipeline:
        - cloud-metadata
      children:
        uk-west:
          children:
            server-1:
              inputs:
                - timestamp: '2024-01-26 00:00:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 89
                - timestamp: '2024-02-26 00:05:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 59
            server-2:
              inputs:
                - timestamp: '2024-02-26 00:00:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                #  cpu/utilization: 110
                - timestamp: '2024-02-26 00:15:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 27
