name: regex
description: successful path
tags:
initialize:
  plugins:
    regex:
      method: Regex
      path: "builtin"
      config:
        parameter: physical-processor
        match: ^(.*),
        output: cpu/name
tree:
  children:
    child:
      pipeline:
        compute:
          - regex
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          physical-processor: Intel® Xeon® Platinum 8272CL,Intel® Xeon® 8171M 2.1 GHz,Intel® Xeon® E5-2673 v4 2.3 GHz,Intel® Xeon® E5-2673 v3 2.4 GHz
