name: mock-observation-demo
description: failure with `config->generators->randint->cpu/utilization->min` is greater than `max`
tags:
initialize:
  plugins:
    mock-observations:
      method: MockObservations
      path: "builtin"
      config:
        timestamp-from: 2023-07-06T00:00
        timestamp-to: 2023-07-06T00:10
        duration: 60
        components:
          - cloud/instance-type: A1
          - cloud/instance-type: B1
        generators:
          common:
            region: uk-west
            common-key: common-val
          randint:
            cpu/utilization:
              min: 99
              max: 10
            memory/utilization:
              min: 1
              max: 99
tree:
  children:
    child:
      pipeline:
        observe:
          - mock-observations
      inputs:
