name: cloud-metadata
description: successful path
tags:
initialize:
  plugins:
    cloud-metadata:
      path: builtin
      method: CSVLookup
      global-config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-aws-instances.csv
        query:
          instance-class: cloud/instance-type
        output: ["cpu-cores-utilized", "vcpus-allocated"]
tree:
  children:
    child:
      pipeline:
        - cloud-metadata
      config:
      inputs:
        - timestamp: 2023-07-06T00:00 # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          cloud/vendor: aws
          cloud/instance-type: m5n.large
          duration: 100
          cpu/utilization: 10
