name: divide
description: failure when `global-config.denominator` is string
tags:
initialize:
  outputs: ['yaml']
  plugins:
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"
    divide:
      method: Divide
      path: "builtin"
      global-config:
        numerator: vcpus-allocated
        denominator: 'vcpus'
        output: cpu/number-cores
    boavizta-cpu:
      method: BoaviztaCpuOutput
      path: "@grnsft/if-unofficial-plugins"
      global-config:
        allocation: LINEAR
        verbose: true
tree:
  children:
    child:
      pipeline:
        - cloud-metadata
        - divide
        - boavizta-cpu
      config:
        divide:
      defaults:
        cloud/vendor: aws
        cloud/instance-type: m5n.large
        cpu/name: Intel® Core™ i7-1185G7
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/utilization: 80
